package org.example.pattern16.hashmaps.freq;

import java.util.HashMap;

/**
 You are given two strings s and t.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Return the letter that was added to t.
 Example 1: Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.

 Example 2:  Input: s = "", t = "y"
 Output: "y"
 */
public class FindDifference {
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }

    public static Character findTheDifference(String s, String t) {
        // Create a HashMap to store character frequencies
        HashMap<Character, Integer> map = new HashMap<>();
        // Count the frequency of characters in string s
        for (char ch : s.toCharArray()) {
            map.put(ch, map.getOrDefault(ch, 0) + 1);
        }
        for (char ch : t.toCharArray()) {
            int freq = map.getOrDefault(ch, 0);
            System.out.println("freq:" + freq);
            if (freq - 1 < 0) {
                return ch;
            }
            map.put(ch, freq - 1);
        }
        return null;
    }

}
